apiVersion: v1
kind: Service
metadata:
  name: products-node-port-service
spec:
  selector:
    app: products-app
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: orders-node-port-service
spec:
  selector:
    app: orders-app
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
