apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders-app
  ports:
  - port: 80
    targetPort: 80
